export const PASSWORD_HISTORY_COUNT = 5;

export const REFRESH_TOKEN_EXPIRY_DAYS = 7;

export const PASSWORD_RESET_TOKEN_EXPIRY_HOURS = 1;

export const MFA_BACKUP_CODES_COUNT = 10;

export const ACCESS_TOKEN_EXPIRY_SECONDS = 900; // 15 min
